# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4a334e8f6e94665a6e5280318bc93a9"
name = "Alt-Magic-app"
handle = "alt-magic-app-1"
application_url = "https://segments-item-shade-evaluating.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products, read_content,unauthenticated_read_content"

[auth]
redirect_urls = ["https://segments-item-shade-evaluating.trycloudflare.com/auth/callback", "https://segments-item-shade-evaluating.trycloudflare.com/auth/shopify/callback", "https://segments-item-shade-evaluating.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
